version: '3'

services:
  postgres:
    image: postgres:15
    container_name: taxi-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taxidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: taxi-api
    command: bash -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/taxidb
      - SECRET_KEY=verysecretkey123
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

volumes:
  postgres_data: